name: main
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.22
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - run: go get
    - run: make lint
    - run: make format && git diff --exit-code
    - run: make test
