name: main
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Lint, format, and test
      run: |

        make lint
        make format
        # Exit if after formatting there are any code differences
        git diff --exit-code

        make test
