apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: php-apache
  name: php-apache
spec:
  replicas: 4
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        imagePullPolicy: Always
        name: php-apache
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpureplicaprint
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpureplicaprint
rules:
- apiGroups:
  - "metrics.k8s.io"
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cpureplicaprint
subjects:
- kind: ServiceAccount
  name: cpureplicaprint
roleRef:
  kind: Role
  name: cpureplicaprint
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cpureplicaprint
  name: cpureplicaprint
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cpureplicaprint
  template:
    metadata:
      labels:
        run: cpureplicaprint
    spec:
      serviceAccountName: cpureplicaprint
      containers:
      - image: cpureplicaprint:latest
        imagePullPolicy: IfNotPresent
        name: cpureplicaprint
      restartPolicy: Always
